version: '3.8'

services:
  mqtt_broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.2
  
  mqtt_broker_boat1:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.3
  
  mqtt_broker_boia1:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.4
  


networks:
  mqtt_network:
    external: true
