version: '3.8'

services:
  mqtt_broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1884:1883"  
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.2
  
  node1:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.3
  
  node2:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.4
  
  node3:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.5
  
  node4:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.6

  node5:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.7
  node6:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.8
  

  node7:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.9


  node8:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.10

  node9:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.11
  

  node10:
    build: .
    command: tail -f /dev/null
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt_network:
        ipv4_address: 192.168.1.12
  

  

networks:
  mqtt_network:
    external: true
